package com.myspace.mdm_poc_workflows;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApproveInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Reject reason")
	private java.lang.String reject_reason;

	@org.kie.api.definition.type.Label("Solution")
	private java.lang.String solution;

	@org.kie.api.definition.type.Label(value = "Is Approve?")
	private java.lang.Boolean is_approved;

	public ApproveInformation() {
	}

	public java.lang.String getReject_reason() {
		return this.reject_reason;
	}

	public void setReject_reason(java.lang.String reject_reason) {
		this.reject_reason = reject_reason;
	}

	public java.lang.String getSolution() {
		return this.solution;
	}

	public void setSolution(java.lang.String solution) {
		this.solution = solution;
	}

	public java.lang.Boolean getIs_approved() {
		return this.is_approved;
	}

	public void setIs_approved(java.lang.Boolean is_approved) {
		this.is_approved = is_approved;
	}

	public ApproveInformation(java.lang.String reject_reason,
			java.lang.String solution, java.lang.Boolean is_approved) {
		this.reject_reason = reject_reason;
		this.solution = solution;
		this.is_approved = is_approved;
	}

}