package com.myspace.mdm_poc_workflows;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerDedupInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Customer code")
	private java.lang.String customer_code;
	@org.kie.api.definition.type.Label(value = "Customer name")
	private java.lang.String customer_name;
	@org.kie.api.definition.type.Label(value = "Error code")
	private java.lang.String error_code;
	@org.kie.api.definition.type.Label(value = "Source")
	private java.lang.String source;
	@org.kie.api.definition.type.Label(value = "Error description")
	private java.lang.String error_desc;
	@org.kie.api.definition.type.Label(value = "CIF created on")
	private java.util.Date cif_created;
	@org.kie.api.definition.type.Label(value = "Branch id")
	private java.lang.String branch_id;
	@org.kie.api.definition.type.Label(value = "Maker id")
	private java.lang.String maker_id;

	public CustomerDedupInfo() {
	}

	public java.lang.String getCustomer_code() {
		return this.customer_code;
	}

	public void setCustomer_code(java.lang.String customer_code) {
		this.customer_code = customer_code;
	}

	public java.lang.String getCustomer_name() {
		return this.customer_name;
	}

	public void setCustomer_name(java.lang.String customer_name) {
		this.customer_name = customer_name;
	}

	public java.lang.String getError_code() {
		return this.error_code;
	}

	public void setError_code(java.lang.String error_code) {
		this.error_code = error_code;
	}

	public java.lang.String getSource() {
		return this.source;
	}

	public void setSource(java.lang.String source) {
		this.source = source;
	}

	public java.lang.String getError_desc() {
		return this.error_desc;
	}

	public void setError_desc(java.lang.String error_desc) {
		this.error_desc = error_desc;
	}

	public java.util.Date getCif_created() {
		return this.cif_created;
	}

	public void setCif_created(java.util.Date cif_created) {
		this.cif_created = cif_created;
	}

	public java.lang.String getBranch_id() {
		return this.branch_id;
	}

	public void setBranch_id(java.lang.String branch_id) {
		this.branch_id = branch_id;
	}

	public java.lang.String getMaker_id() {
		return this.maker_id;
	}

	public void setMaker_id(java.lang.String maker_id) {
		this.maker_id = maker_id;
	}

	public CustomerDedupInfo(java.lang.String customer_code,
			java.lang.String customer_name, java.lang.String error_code,
			java.lang.String source, java.lang.String error_desc,
			java.util.Date cif_created, java.lang.String branch_id,
			java.lang.String maker_id) {
		this.customer_code = customer_code;
		this.customer_name = customer_name;
		this.error_code = error_code;
		this.source = source;
		this.error_desc = error_desc;
		this.cif_created = cif_created;
		this.branch_id = branch_id;
		this.maker_id = maker_id;
	}

}