package com.myspace.mdm_poc_workflows;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DeDuplicateInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Customer 1")
	private com.myspace.mdm_poc_workflows.CustomerDedupInfo customer1;
	@org.kie.api.definition.type.Label("Customer 2")
	private com.myspace.mdm_poc_workflows.CustomerDedupInfo customer2;
	@org.kie.api.definition.type.Label("Customer 3")
	private com.myspace.mdm_poc_workflows.CustomerDedupInfo customer3;
	@org.kie.api.definition.type.Label("Customer 4")
	private com.myspace.mdm_poc_workflows.CustomerDedupInfo customer4;

	@org.kie.api.definition.type.Label("Process Approval")
	private com.myspace.mdm_poc_workflows.ApproveInformation processApproval;

	public DeDuplicateInfo() {
		this.customer1 = new com.myspace.mdm_poc_workflows.CustomerDedupInfo();
		this.customer2 = new com.myspace.mdm_poc_workflows.CustomerDedupInfo();
		this.customer3 = new com.myspace.mdm_poc_workflows.CustomerDedupInfo();
		this.customer4 = new com.myspace.mdm_poc_workflows.CustomerDedupInfo();
		this.processApproval = new com.myspace.mdm_poc_workflows.ApproveInformation();
	}

	public com.myspace.mdm_poc_workflows.CustomerDedupInfo getCustomer1() {
		return this.customer1;
	}

	public void setCustomer1(
			com.myspace.mdm_poc_workflows.CustomerDedupInfo customer1) {
		this.customer1 = customer1;
	}

	public com.myspace.mdm_poc_workflows.CustomerDedupInfo getCustomer2() {
		return this.customer2;
	}

	public void setCustomer2(
			com.myspace.mdm_poc_workflows.CustomerDedupInfo customer2) {
		this.customer2 = customer2;
	}

	public com.myspace.mdm_poc_workflows.CustomerDedupInfo getCustomer3() {
		return this.customer3;
	}

	public void setCustomer3(
			com.myspace.mdm_poc_workflows.CustomerDedupInfo customer3) {
		this.customer3 = customer3;
	}

	public com.myspace.mdm_poc_workflows.CustomerDedupInfo getCustomer4() {
		return this.customer4;
	}

	public void setCustomer4(
			com.myspace.mdm_poc_workflows.CustomerDedupInfo customer4) {
		this.customer4 = customer4;
	}

	public com.myspace.mdm_poc_workflows.ApproveInformation getProcessApproval() {
		return this.processApproval;
	}

	public void setProcessApproval(
			com.myspace.mdm_poc_workflows.ApproveInformation processApproval) {
		this.processApproval = processApproval;
	}

	public DeDuplicateInfo(
			com.myspace.mdm_poc_workflows.CustomerDedupInfo customer1,
			com.myspace.mdm_poc_workflows.CustomerDedupInfo customer2,
			com.myspace.mdm_poc_workflows.CustomerDedupInfo customer3,
			com.myspace.mdm_poc_workflows.CustomerDedupInfo customer4,
			com.myspace.mdm_poc_workflows.ApproveInformation processApproval) {
		this.customer1 = customer1;
		this.customer2 = customer2;
		this.customer3 = customer3;
		this.customer4 = customer4;
		this.processApproval = processApproval;
	}

}