package com.myspace.mdm_poc_workflows;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DssInvalidData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Source")
	private java.lang.String source;
	@org.kie.api.definition.type.Label("COB Date")
	private java.util.Date cob_date;
	@org.kie.api.definition.type.Label("Số CIF")
	@org.kie.api.definition.type.Description("Khóa chính của table Master")
	private java.lang.String kdi01;
	@org.kie.api.definition.type.Label("Họ tên KH")
	@org.kie.api.definition.type.Description("POC only, cần lookup vào table Master để lấy thông tin cần thiết")
	private java.lang.String kdi02;
	@org.kie.api.definition.type.Label("Column lỗi (Code)")
	private java.lang.String error_column;
	@org.kie.api.definition.type.Label("Value lỗi")
	private java.lang.String error_value;
	@org.kie.api.definition.type.Label("Error DSS code (PK)")
	@org.kie.api.definition.type.Description("Khóa chính, gồm Source + Kdi001 + error_column")
	private java.lang.String error_dss_code;
	@org.kie.api.definition.type.Label("Mã lỗi")
	@org.kie.api.definition.type.Description("Danh sách các mã lỗi, phân cách bằng dấu phẩy \",\"")
	private java.lang.String error_code;
	@org.kie.api.definition.type.Label("Số lỗi")
	@org.kie.api.definition.type.Description("Đếm số mã lỗi trong error_code")
	private int invalid_count;
	@org.kie.api.definition.type.Label("Branch Id")
	private java.lang.String branch_id;
	@org.kie.api.definition.type.Label("User Id")
	private java.lang.String user_id;

	@org.kie.api.definition.type.Label("Approve?")
	private java.lang.Boolean approve_flag;

	@org.kie.api.definition.type.Label("Value mới")
	private java.lang.String input_value;

	@org.kie.api.definition.type.Label(value = "Lý do từ chối")
	private java.lang.String reject_reason;

	public DssInvalidData() {
	}

	public java.lang.String getSource() {
		return this.source;
	}

	public void setSource(java.lang.String source) {
		this.source = source;
	}

	public java.util.Date getCob_date() {
		return this.cob_date;
	}

	public void setCob_date(java.util.Date cob_date) {
		this.cob_date = cob_date;
	}

	public java.lang.String getKdi01() {
		return this.kdi01;
	}

	public void setKdi01(java.lang.String kdi01) {
		this.kdi01 = kdi01;
	}

	public java.lang.String getKdi02() {
		return this.kdi02;
	}

	public void setKdi02(java.lang.String kdi02) {
		this.kdi02 = kdi02;
	}

	public java.lang.String getError_column() {
		return this.error_column;
	}

	public void setError_column(java.lang.String error_column) {
		this.error_column = error_column;
	}

	public java.lang.String getError_value() {
		return this.error_value;
	}

	public void setError_value(java.lang.String error_value) {
		this.error_value = error_value;
	}

	public java.lang.String getError_dss_code() {
		return this.error_dss_code;
	}

	public void setError_dss_code(java.lang.String error_dss_code) {
		this.error_dss_code = error_dss_code;
	}

	public java.lang.String getError_code() {
		return this.error_code;
	}

	public void setError_code(java.lang.String error_code) {
		this.error_code = error_code;
	}

	public int getInvalid_count() {
		return this.invalid_count;
	}

	public void setInvalid_count(int invalid_count) {
		this.invalid_count = invalid_count;
	}

	public java.lang.String getBranch_id() {
		return this.branch_id;
	}

	public void setBranch_id(java.lang.String branch_id) {
		this.branch_id = branch_id;
	}

	public java.lang.String getUser_id() {
		return this.user_id;
	}

	public void setUser_id(java.lang.String user_id) {
		this.user_id = user_id;
	}

	public java.lang.Boolean getApprove_flag() {
		return this.approve_flag;
	}

	public void setApprove_flag(java.lang.Boolean approve_flag) {
		this.approve_flag = approve_flag;
	}

	public java.lang.String getInput_value() {
		return this.input_value;
	}

	public void setInput_value(java.lang.String input_value) {
		this.input_value = input_value;
	}

	public java.lang.String getReject_reason() {
		return this.reject_reason;
	}

	public void setReject_reason(java.lang.String reject_reason) {
		this.reject_reason = reject_reason;
	}

	public DssInvalidData(java.lang.String source, java.util.Date cob_date,
			java.lang.String kdi01, java.lang.String kdi02,
			java.lang.String error_column, java.lang.String error_value,
			java.lang.String error_dss_code, java.lang.String error_code,
			int invalid_count, java.lang.String branch_id,
			java.lang.String user_id, java.lang.Boolean approve_flag,
			java.lang.String input_value, java.lang.String reject_reason) {
		this.source = source;
		this.cob_date = cob_date;
		this.kdi01 = kdi01;
		this.kdi02 = kdi02;
		this.error_column = error_column;
		this.error_value = error_value;
		this.error_dss_code = error_dss_code;
		this.error_code = error_code;
		this.invalid_count = invalid_count;
		this.branch_id = branch_id;
		this.user_id = user_id;
		this.approve_flag = approve_flag;
		this.input_value = input_value;
		this.reject_reason = reject_reason;
	}

}