package com.myspace.mdm_poc_workflows;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MdmProduct implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Product id")
	private java.lang.Integer product_id;
	@org.kie.api.definition.type.Label("Domain id")
	private java.lang.Integer domain_id;
	@org.kie.api.definition.type.Label("Category Id")
	private java.lang.Integer category_id;
	@org.kie.api.definition.type.Label("Product name")
	private java.lang.String product_name;
	@org.kie.api.definition.type.Label("Doi tuong ap dung")
	private java.lang.String doi_tuong_ap_dung;
	@org.kie.api.definition.type.Label("Kenh")
	private java.lang.String kenh;
	@org.kie.api.definition.type.Label("Description ")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("From date")
	private java.util.Date from_date;
	@org.kie.api.definition.type.Label("To date")
	private java.util.Date to_date;
	@org.kie.api.definition.type.Label("Status")
	private java.lang.Boolean status;
	@org.kie.api.definition.type.Label("Approve?")
	private java.lang.Boolean is_approved;

	@org.kie.api.definition.type.Label("Attribute Json")
	private java.lang.String attribute_json;

	@org.kie.api.definition.type.Label("Fees Json")
	private java.lang.String fees_json;

	@org.kie.api.definition.type.Label("Promotion Json")
	private java.lang.String promotion_json;

	@org.kie.api.definition.type.Label(value = "Reject reason")
	private java.lang.String reject_reason;

	public MdmProduct() {
	}

	public java.lang.Integer getProduct_id() {
		return this.product_id;
	}

	public void setProduct_id(java.lang.Integer product_id) {
		this.product_id = product_id;
	}

	public java.lang.Integer getDomain_id() {
		return this.domain_id;
	}

	public void setDomain_id(java.lang.Integer domain_id) {
		this.domain_id = domain_id;
	}

	public java.lang.Integer getCategory_id() {
		return this.category_id;
	}

	public void setCategory_id(java.lang.Integer category_id) {
		this.category_id = category_id;
	}

	public java.lang.String getProduct_name() {
		return this.product_name;
	}

	public void setProduct_name(java.lang.String product_name) {
		this.product_name = product_name;
	}

	public java.lang.String getDoi_tuong_ap_dung() {
		return this.doi_tuong_ap_dung;
	}

	public void setDoi_tuong_ap_dung(java.lang.String doi_tuong_ap_dung) {
		this.doi_tuong_ap_dung = doi_tuong_ap_dung;
	}

	public java.lang.String getKenh() {
		return this.kenh;
	}

	public void setKenh(java.lang.String kenh) {
		this.kenh = kenh;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.util.Date getFrom_date() {
		return this.from_date;
	}

	public void setFrom_date(java.util.Date from_date) {
		this.from_date = from_date;
	}

	public java.util.Date getTo_date() {
		return this.to_date;
	}

	public void setTo_date(java.util.Date to_date) {
		this.to_date = to_date;
	}

	public java.lang.Boolean getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Boolean status) {
		this.status = status;
	}

	public java.lang.Boolean getIs_approved() {
		return this.is_approved;
	}

	public void setIs_approved(java.lang.Boolean is_approved) {
		this.is_approved = is_approved;
	}

	public java.lang.String getAttribute_json() {
		return this.attribute_json;
	}

	public void setAttribute_json(java.lang.String attribute_json) {
		this.attribute_json = attribute_json;
	}

	public java.lang.String getFees_json() {
		return this.fees_json;
	}

	public void setFees_json(java.lang.String fees_json) {
		this.fees_json = fees_json;
	}

	public java.lang.String getPromotion_json() {
		return this.promotion_json;
	}

	public void setPromotion_json(java.lang.String promotion_json) {
		this.promotion_json = promotion_json;
	}

	public java.lang.String getReject_reason() {
		return this.reject_reason;
	}

	public void setReject_reason(java.lang.String reject_reason) {
		this.reject_reason = reject_reason;
	}

	public MdmProduct(java.lang.Integer product_id,
			java.lang.Integer domain_id, java.lang.Integer category_id,
			java.lang.String product_name, java.lang.String doi_tuong_ap_dung,
			java.lang.String kenh, java.lang.String description,
			java.util.Date from_date, java.util.Date to_date,
			java.lang.Boolean status, java.lang.Boolean is_approved,
			java.lang.String attribute_json, java.lang.String fees_json,
			java.lang.String promotion_json, java.lang.String reject_reason) {
		this.product_id = product_id;
		this.domain_id = domain_id;
		this.category_id = category_id;
		this.product_name = product_name;
		this.doi_tuong_ap_dung = doi_tuong_ap_dung;
		this.kenh = kenh;
		this.description = description;
		this.from_date = from_date;
		this.to_date = to_date;
		this.status = status;
		this.is_approved = is_approved;
		this.attribute_json = attribute_json;
		this.fees_json = fees_json;
		this.promotion_json = promotion_json;
		this.reject_reason = reject_reason;
	}

}