package com.myspace.mdm_poc_workflows;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleFieldConfig implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Rule type")
	private java.lang.String rule_type;
	@org.kie.api.definition.type.Label("Rule code")
	private java.lang.String rule_code;
	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("Valid to date")
	private java.util.Date to_date;
	@org.kie.api.definition.type.Label("Valid from date")
	private java.util.Date from_date;
	@org.kie.api.definition.type.Label("Product type")
	private java.lang.String product_type;
	@org.kie.api.definition.type.Label("Operating system")
	private java.lang.String operating_system;
	@org.kie.api.definition.type.Label("Column apply")
	private java.lang.String column_apply;
	@org.kie.api.definition.type.Label("Is invalid warning null")
	private java.lang.Boolean is_invalid_warning_null;
	@org.kie.api.definition.type.Label("Match run order")
	private java.lang.Integer match_run_order;
	@org.kie.api.definition.type.Label("Merge master os")
	private java.lang.String merge_master_os;
	@org.kie.api.definition.type.Label("Merge priority os")
	private java.lang.String merge_priority_os;
	@org.kie.api.definition.type.Label("Merge is use time priority")
	private java.lang.Boolean merge_is_use_time_priority;

	@org.kie.api.definition.type.Label("Is rule field config?")
	private java.lang.Boolean rule_field_config;

	@org.kie.api.definition.type.Label("Approve?")
	private java.lang.Boolean approve_flag;

	@org.kie.api.definition.type.Label("Reject reason")
	private java.lang.String reject_reason;

	@org.kie.api.definition.type.Label(value = "Merge group")
	private java.lang.String merge_group;

	public RuleFieldConfig() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getRule_type() {
		return this.rule_type;
	}

	public void setRule_type(java.lang.String rule_type) {
		this.rule_type = rule_type;
	}

	public java.lang.String getRule_code() {
		return this.rule_code;
	}

	public void setRule_code(java.lang.String rule_code) {
		this.rule_code = rule_code;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.util.Date getTo_date() {
		return this.to_date;
	}

	public void setTo_date(java.util.Date to_date) {
		this.to_date = to_date;
	}

	public java.util.Date getFrom_date() {
		return this.from_date;
	}

	public void setFrom_date(java.util.Date from_date) {
		this.from_date = from_date;
	}

	public java.lang.String getProduct_type() {
		return this.product_type;
	}

	public void setProduct_type(java.lang.String product_type) {
		this.product_type = product_type;
	}

	public java.lang.String getOperating_system() {
		return this.operating_system;
	}

	public void setOperating_system(java.lang.String operating_system) {
		this.operating_system = operating_system;
	}

	public java.lang.String getColumn_apply() {
		return this.column_apply;
	}

	public void setColumn_apply(java.lang.String column_apply) {
		this.column_apply = column_apply;
	}

	public java.lang.Boolean getIs_invalid_warning_null() {
		return this.is_invalid_warning_null;
	}

	public void setIs_invalid_warning_null(
			java.lang.Boolean is_invalid_warning_null) {
		this.is_invalid_warning_null = is_invalid_warning_null;
	}

	public java.lang.Integer getMatch_run_order() {
		return this.match_run_order;
	}

	public void setMatch_run_order(java.lang.Integer match_run_order) {
		this.match_run_order = match_run_order;
	}

	public java.lang.String getMerge_master_os() {
		return this.merge_master_os;
	}

	public void setMerge_master_os(java.lang.String merge_master_os) {
		this.merge_master_os = merge_master_os;
	}

	public java.lang.String getMerge_priority_os() {
		return this.merge_priority_os;
	}

	public void setMerge_priority_os(java.lang.String merge_priority_os) {
		this.merge_priority_os = merge_priority_os;
	}

	public java.lang.Boolean getMerge_is_use_time_priority() {
		return this.merge_is_use_time_priority;
	}

	public void setMerge_is_use_time_priority(
			java.lang.Boolean merge_is_use_time_priority) {
		this.merge_is_use_time_priority = merge_is_use_time_priority;
	}

	public java.lang.Boolean getRule_field_config() {
		return this.rule_field_config;
	}

	public void setRule_field_config(java.lang.Boolean rule_field_config) {
		this.rule_field_config = rule_field_config;
	}

	public java.lang.Boolean getApprove_flag() {
		return this.approve_flag;
	}

	public void setApprove_flag(java.lang.Boolean approve_flag) {
		this.approve_flag = approve_flag;
	}

	public java.lang.String getReject_reason() {
		return this.reject_reason;
	}

	public void setReject_reason(java.lang.String reject_reason) {
		this.reject_reason = reject_reason;
	}

	public java.lang.String getMerge_group() {
		return this.merge_group;
	}

	public void setMerge_group(java.lang.String merge_group) {
		this.merge_group = merge_group;
	}

	public RuleFieldConfig(java.lang.String id, java.lang.String rule_type,
			java.lang.String rule_code, java.lang.String description,
			java.util.Date to_date, java.util.Date from_date,
			java.lang.String product_type, java.lang.String operating_system,
			java.lang.String column_apply,
			java.lang.Boolean is_invalid_warning_null,
			java.lang.Integer match_run_order,
			java.lang.String merge_master_os,
			java.lang.String merge_priority_os,
			java.lang.Boolean merge_is_use_time_priority,
			java.lang.Boolean rule_field_config,
			java.lang.Boolean approve_flag, java.lang.String reject_reason,
			java.lang.String merge_group) {
		this.id = id;
		this.rule_type = rule_type;
		this.rule_code = rule_code;
		this.description = description;
		this.to_date = to_date;
		this.from_date = from_date;
		this.product_type = product_type;
		this.operating_system = operating_system;
		this.column_apply = column_apply;
		this.is_invalid_warning_null = is_invalid_warning_null;
		this.match_run_order = match_run_order;
		this.merge_master_os = merge_master_os;
		this.merge_priority_os = merge_priority_os;
		this.merge_is_use_time_priority = merge_is_use_time_priority;
		this.rule_field_config = rule_field_config;
		this.approve_flag = approve_flag;
		this.reject_reason = reject_reason;
		this.merge_group = merge_group;
	}

}